In [30]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"

# Fetch the HTML content
response = requests.get(url)
response.raise_for_status()

# Parse the HTML content
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table element (adjust selector if needed)
table = soup.find('table')

# Extract table data into a DataFrame and skip the first
# row to avoid header duplication
df = pd.read_html(str(table), skiprows=0)[0]

# Drop this columns
df.drop(columns=["State-owned", "Ref."], inplace=True)

# Rename Headquarters Column name
df.rename(columns={
    "Headquarters[note 1]": "Headquarters"
    }, inplace=True)

# Explicitly set the column names
df.columns = ['Rank', 'Name', 'Industry', 'Revenue USD millions', 'Profit USD millions',
       'Employees', 'Headquarters', 'Revenue per worker']
# Save the DataFrame to a CSV file
df.to_csv("largest_companies_revenue.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

<ipython-input-30-908a24201e52>:22: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  df.drop(columns=["State-owned", "Ref."], inplace=True)

In [31]:
import pandas as pd
df = pd.read_csv('largest_companies_revenue.csv')
df.head()

,Rank,Name,Industry,Revenue USD millions,Profit USD millions,Employees,Headquarters,Revenue per worker
0,1,Walmart,Retail,"$611,289","$11,680",2100000,United States,"$291,090.00"
1,2,Saudi Aramco,Oil and gas,"$603,651","$159,069",70496,Saudi Arabia,"$8,562,911.37"
2,3,Amazon,Retail,"$574,785","$30,425",1525000,United States,"$376,908.20"
3,4,State Grid Corporation of China,Electricity,"$530,009","$8,192",870287,China,"$609,004.85"
4,5,Vitol,Commodities,"$505,000","$15,000",1560,Switzerland,"$323,717,948.72"

In [32]:
df.columns

Index(['Rank', 'Name', 'Industry', 'Revenue USD millions',
       'Profit USD millions', 'Employees', 'Headquarters',
       'Revenue per worker'],
      dtype='object')